# Generated by Django 3.2.8 on 2021-11-16 12:54

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='favicon',
            field=models.ImageField(default=1, upload_to=client.models.user_image),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='short_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='slogan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
