# Generated by Django 3.2.8 on 2021-10-21 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevitrin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coursevitrin',
            name='status',
        ),
        migrations.AddField(
            model_name='coursevitrin',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursevitrin',
            name='lesson_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursevitrin',
            name='price',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursevitrin',
            name='price_with_discount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursevitrin',
            name='teacher',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursevitrin',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='domain',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='org_colore',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sub_colore',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofestablishment',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='CourseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.coursevitrin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
