# Generated by Django 3.2.8 on 2021-10-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20211021_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='kuberid',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
