# Generated by Django 3.2.8 on 2021-11-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20211116_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetag',
            name='currenttag',
        ),
        migrations.RemoveField(
            model_name='imagetag',
            name='releasetag',
        ),
        migrations.RemoveField(
            model_name='imagetag',
            name='user',
        ),
        migrations.AddField(
            model_name='imagetag',
            name='admin_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetag',
            name='admin_version',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetag',
            name='android_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetag',
            name='android_version',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetag',
            name='forceupdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='ios_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetag',
            name='ios_version',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetag',
            name='pwa_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetag',
            name='pwa_version',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetag',
            name='site_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetag',
            name='site_version',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetag',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='smsir_key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='zarinpal',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
