# Generated by Django 3.2.8 on 2021-10-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_setting_kuberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateofestablishment',
            field=models.DateField(null=True),
        ),
    ]
