# Generated by Django 3.2.8 on 2021-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_user_dateofestablishment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verfication_status',
        ),
        migrations.AddField(
            model_name='setting',
            name='admin_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='fullname',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='pwa_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='site_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
