# Generated by Django 3.2.8 on 2021-11-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20211117_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseUser',
        ),
        migrations.DeleteModel(
            name='CourseVitrin',
        ),
    ]
