# Generated by Django 3.2.8 on 2021-10-31 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20211027_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='company_logo',
            field=models.FileField(default=1, upload_to='userdoc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='contact_phone',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='download_link',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='image_tag',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='splashscreen',
            field=models.FileField(default=1, upload_to='userdoc'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Imagetag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currenttag', models.CharField(max_length=20, null=True)),
                ('releasetag', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
