# Generated by Django 3.2.8 on 2021-11-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20211117_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='user',
            new_name='owner',
        ),
    ]
