# Generated by Django 3.2.8 on 2021-11-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_rename_user_setting_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='org_colore',
            new_name='org_color',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='sub_colore',
            new_name='sub_color',
        ),
    ]
