# Generated by Django 3.2.8 on 2021-10-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20211031_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='admin_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='company_logo',
            field=models.ImageField(upload_to='user_doc'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='fullname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='kuberid',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='pwa_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='splashscreen',
            field=models.ImageField(upload_to='user_doc'),
        ),
    ]
