# Generated by Django 3.2.8 on 2021-11-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20211118_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='image_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.imagetag'),
            preserve_default=False,
        ),
    ]
