# Generated by Django 3.2.8 on 2021-10-31 15:44

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20211031_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='company_logo',
            field=models.ImageField(upload_to=client.models.user_image),
        ),
        migrations.AlterField(
            model_name='setting',
            name='splashscreen',
            field=models.ImageField(upload_to=client.models.user_image),
        ),
    ]
