# Generated by Django 3.2.8 on 2021-10-31 16:23

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20211031_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='company_logo',
            field=models.FileField(upload_to=client.models.user_image),
        ),
    ]
