# Generated by Django 3.2.8 on 2021-11-02 15:41

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_setting_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='company_logo',
            field=models.ImageField(upload_to=client.models.user_image),
        ),
        migrations.AlterField(
            model_name='user',
            name='educational_interface_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
