# Generated by Django 4.0.4 on 2022-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_setting_image_tag_passwordgenerator'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.IntegerField()),
                ('trying', models.IntegerField(default=0)),
            ],
        ),
    ]
