# Generated by Django 4.0.4 on 2022-05-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra',
            field=models.JSONField(default=dict),
        ),
    ]
