# Generated by Django 3.2.8 on 2021-11-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20211102_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='educational_interface_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_name',
            field=models.CharField(max_length=15),
        ),
    ]
