# Generated by Django 3.2.8 on 2021-11-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20211108_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='educational_interface_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
