# Generated by Django 4.0.4 on 2022-06-05 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_user_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='image_tag',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.imagetag'),
        ),
    ]
