# Generated by Django 3.2.8 on 2021-11-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_user_educational_interface_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='sub_domain',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
