# Generated by Django 3.2.8 on 2021-11-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_setting_sub_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='sub_domain',
        ),
    ]
