# Generated by Django 3.2.8 on 2021-11-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_remove_setting_sub_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='active_user',
            field=models.BooleanField(default=False),
        ),
    ]
