# Generated by Django 3.2.8 on 2021-11-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courseuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseuser',
            old_name='user',
            new_name='owner',
        ),
    ]
