# Generated by Django 4.0.6 on 2022-07-20 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.orderitem'),
        ),
    ]
