# Generated by Django 4.0.6 on 2022-07-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pay_date',
            field=models.DateTimeField(null=True),
        ),
    ]
