# Generated by Django 4.0.6 on 2022-07-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='owner',
        ),
    ]
